language: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t vangalasantosh06/react-test -f ./client/Dockerfile.dev ./client


after_success:
    - docker build -t vangalasantosh06/multi-client ./client
    - docker build -t vangalasantosh06/multi-nginx ./nginx
    - docker build -t vangalasantosh06/multi-server ./server
    - docker build -t vangalasantosh06/multi-worker ./worker

    #login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take images and push to dockerhub
    - docker push vangalasantosh06/multi-client
    - docker push vangalasantosh06/multi-nginx
    - docker push vangalasantosh06/multi-server
    - docker push vangalasantosh06/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-938421679085
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY